language: python
python: 3.7
dist: xenial
sudo: required

stage: test
env:
  global:
    - PYPI_USERNAME=SethMichaelLarson
    # PYPI_PASSWORD is set in the Travis settings

install:
  - python -m pip install nox

stages:
  - name: test
    if: type != cron
  - name: cron
    if: type = cron

jobs:
  include:
    - script: python -m nox -s check
    - script: python -m nox -s test
      env: DEPLOY=1

    - script: .travis/cron.sh
      stage: cron


deploy:
  provider: script
  skip_cleanup: true
  script: python -m nox -s deploy
  on:
    condition: $DEPLOY = 1
    branch: master
    repo: python-http/hstspreload

