name: CI

on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3.8 -m pip install nox
      - name: Lint the code
        run: nox -s lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3.8 -m pip install nox
      - name: Install dependencies1
        run: python3.8 -m pip install virtualenv==20.3.1
      - name: Install dependencies2
        run: python3.8 -m pip install colorlog==4.7.2
      - name: Test the code
        run: nox -s test
